name: Deploy
on:
  workflow_dispatch:
  push:
    branches-ignore: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == false) || github.event_name != 'pull_request'
    permissions:
      contents: write
      deployments: write
      pull-requests: write
      statuses: write
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Quarto
        id: quarto-setup
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2

      - name: Set up R (for code-link option)
        id: r-setup
        uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2

      - name: Install packages
        id: install-pkgs
        run: Rscript -e 'install.packages(c("rmarkdown", "downlit", "xml2"))'

      - name: Render
        id: render
        uses: quarto-dev/quarto-actions/render@8a96df13519ee81fd526f2dfca5962811136661b # v2

      # https://dev.to/hectorleiva/github-actions-and-creating-a-short-sha-hash-8b7
      - name: Set short git commit SHA
        id: short-sha
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Deploy to Netlify
        id: deploy
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './_site'
          production-branch: main
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions - ${{ env.DEPLOY_SOURCE }}"
          enable-pull-request-comment: true
          overwrites-pull-request-comment: true
          alias: ${{ env.DEPLOY_SOURCE }}
        env:
          DEPLOY_SOURCE: ${{ github.head_ref ||  env.COMMIT_SHORT_SHA  }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 2
