name: Publish
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.event.pull_request.merged == true
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2
      - name: Set up R (for code-link option)
        id: r-setup
        uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2

      - name: Install packages
        id: install-pkgs
        run: Rscript -e 'install.packages(c("rmarkdown", "downlit", "xml2"))'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@8a96df13519ee81fd526f2dfca5962811136661b # v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
